name: Daily Run of papyrus

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade importlib-metadata pydantic openai
        pip install -r requirements.txt

    - name: Run main.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        PYTHONPATH: ${{ github.workspace }}
        CONFIG_PATH: "src/config/config.yaml"
        PROJECT_PATH: ""
      run: |
        python src/main.py

  deploy-to-vercel:
    needs: run-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Vercel CLI
        uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/
      
      - name: Deploy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
